/**
 * devsetgo — README Generator
 *
 * Orchestrates README generation with the CRO framework.
 */

import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve, join, relative } from 'node:path';
import { createLogger } from '../utils/logger.js';
import { safeWriteFile } from '../utils/file-system.js';
import { generateCROReadme } from './cro-framework.js';
import type { ProjectManifest, DevSetGoConfig, ReadmeResult } from '../parser/types.js';

const logger = createLogger('readme');

/**
 * Marker embedded in every README devsetgo writes.
 *
 * Its presence is how we tell "a file we previously generated, safe to
 * regenerate" apart from "a README a human wrote, do not touch".
 */
export const GENERATED_MARKER = '<!-- devsetgo:generated -->';

/**
 * Raised when generating would destroy a README devsetgo did not write.
 */
export class ReadmeOverwriteError extends Error {
  constructor(public readonly outputPath: string) {
    super(
      `Refusing to overwrite an existing README that devsetgo did not generate:\n` +
        `  ${outputPath}\n\n` +
        `This file has no devsetgo marker, so it was most likely written by hand.\n` +
        `Choose one:\n` +
        `  • devsetgo readme --force        overwrite it (a .bak copy is kept)\n` +
        `  • devsetgo readme -o DRAFT.md    write somewhere else\n` +
        `  • set readme.output in your devsetgo config`,
    );
    this.name = 'ReadmeOverwriteError';
  }
}

export interface GenerateReadmeOptions {
  /** Overwrite a hand-written README. A .bak copy is written first. */
  force?: boolean;
}

/**
 * Decide whether `outputPath` may be written.
 *
 * Returns whether a backup should be taken first. Throws if the existing file
 * is hand-written and `force` was not passed.
 */
async function checkOverwriteAllowed(
  outputPath: string,
  force: boolean,
): Promise<{ needsBackup: boolean }> {
  if (!existsSync(outputPath)) {
    return { needsBackup: false };
  }

  let existing: string;
  try {
    existing = await readFile(outputPath, 'utf-8');
  } catch {
    // Unreadable but present — treat as hand-written and refuse without --force.
    if (!force) throw new ReadmeOverwriteError(outputPath);
    return { needsBackup: true };
  }

  // Previously generated by us: regenerating is the expected workflow.
  if (existing.includes(GENERATED_MARKER)) {
    return { needsBackup: false };
  }

  if (!force) throw new ReadmeOverwriteError(outputPath);

  return { needsBackup: true };
}

/**
 * Generate a CRO-optimized README.
 */
export async function generateReadme(
  rootDir: string,
  manifest: ProjectManifest,
  config: DevSetGoConfig,
  options: GenerateReadmeOptions = {},
): Promise<ReadmeResult> {
  const absRoot = resolve(rootDir);
  const outputPath = join(absRoot, config.readme.output);

  logger.info(`Generating README at ${config.readme.output}`);

  const { needsBackup } = await checkOverwriteAllowed(outputPath, options.force === true);

  let content: string;
  let sections: string[];

  if (config.readme.cro_enabled) {
    // Full CRO framework
    const result = generateCROReadme(manifest, config);
    content = result.content;
    sections = result.sections;
  } else {
    // Simple README without CRO
    content = generateSimpleReadme(manifest, config);
    sections = ['header', 'quick-start', 'license'];
  }

  content = `${GENERATED_MARKER}\n${content}`;

  if (needsBackup) {
    logger.warn(`Backing up existing README to ${relative(absRoot, outputPath)}.bak`);
  }

  await safeWriteFile(outputPath, content, { overwrite: true, backup: needsBackup });

  logger.success(`README generated with ${sections.length} sections`);

  return {
    outputPath,
    content,
    sections,
  };
}

/**
 * Generate a simple README without CRO framework.
 */
function generateSimpleReadme(manifest: ProjectManifest, config: DevSetGoConfig): string {
  return `# ${config.project.name}

${config.project.description}

## Quick Start

\`\`\`bash
${config.readme.quick_start.install_command}
${config.readme.quick_start.first_run}
\`\`\`

## License

MIT
`;
}

export default generateReadme;
