/**
 * devsetgo — Init Command
 *
 * Interactive project initialization that scans the repo and generates config.
 */

import { join, resolve } from 'node:path';
import { existsSync } from 'node:fs';
import { log } from '../utils/logger.js';
import {
  findCodeFiles,
  findOpenAPIFiles,
  findMarkdownFiles,
  ensureDir,
  safeWriteFile,
  readFileContent,
} from '../utils/file-system.js';
import { stringify as yamlStringify } from 'yaml';

interface InitOptions {
  force?: boolean;
  config?: string;
  verbose?: boolean;
}

export async function initCommand(cwd: string, options: InitOptions): Promise<void> {
  const absRoot = resolve(cwd);
  log.banner('devsetgo init');

  // Check for existing config
  const configPath = join(absRoot, 'devsetgo.config.yaml');
  if (existsSync(configPath) && !options.force) {
    log.warn('Configuration already exists. Use --force to overwrite.');
    return;
  }

  log.info('Scanning project structure...');

  // 1. Scan the project
  const [codeFiles, openAPIFiles, markdownFiles] = await Promise.all([
    findCodeFiles(absRoot),
    findOpenAPIFiles(absRoot),
    findMarkdownFiles(absRoot),
  ]);

  log.success(`Found ${codeFiles.length} source files`);
  log.success(`Found ${openAPIFiles.length} OpenAPI schemas`);
  log.success(`Found ${markdownFiles.length} Markdown files`);

  // 2. Auto-detect project info
  let projectName = '';
  let projectDesc = '';
  let projectRepo = '';
  let installCommand = '';

  const packageJsonPath = join(absRoot, 'package.json');
  if (existsSync(packageJsonPath)) {
    try {
      const pkg = JSON.parse(await readFileContent(packageJsonPath));
      projectName = pkg.name || '';
      projectDesc = pkg.description || '';
      installCommand = pkg.name ? `npm install ${pkg.name}` : '';
      if (pkg.repository) {
        projectRepo =
          typeof pkg.repository === 'string'
            ? pkg.repository
            : pkg.repository.url?.replace(/^git\+/, '').replace(/\.git$/, '') || '';
      }
    } catch {
      // Ignore
    }
  }

  // 3. Detect languages
  const languages = new Set<string>();
  for (const file of codeFiles) {
    if (file.endsWith('.ts') || file.endsWith('.tsx')) languages.add('typescript');
    if (file.endsWith('.js') || file.endsWith('.jsx')) languages.add('javascript');
    if (file.endsWith('.py')) languages.add('python');
    if (file.endsWith('.rs')) languages.add('rust');
    if (file.endsWith('.go')) languages.add('go');
  }

  // 4. Generate config
  const config = {
    project: {
      name: projectName || 'my-project',
      description: projectDesc || 'A developer tool that does amazing things.',
      repo: projectRepo || 'https://github.com/your-org/your-repo',
      version: '1.0.0',
    },
    playground: {
      theme: 'dark',
      title: `${projectName || 'My Project'} — Interactive Playground`,
      languages: languages.size > 0 ? [...languages] : ['javascript'],
      output_dir: '.devsetgo/playground',
    },
    readme: {
      cro_enabled: true,
      output: 'README.md',
      format: 'github',
      hero: {
        tagline: projectDesc || 'TODO: Write a compelling one-line value proposition.',
        badges: [{ type: 'build', status: 'passing' }, { type: 'version' }, { type: 'license' }],
      },
      problem: 'TODO: Describe the specific pain point your tool solves.',
      solution: 'TODO: Explain how your tool solves the problem.',
      quick_start: {
        install_command: installCommand || 'npm install your-package',
        first_run: 'npx your-package init',
      },
      features: [
        {
          name: 'Feature One',
          description: 'TODO: Describe this feature.',
          status: 'stable',
        },
      ],
      metrics: [],
    },
    cta: {
      install: {
        command: installCommand || 'npm install your-package',
        label: 'Get Started in 30 Seconds',
      },
      enterprise: {
        enabled: true,
        url: 'https://calendly.com/your-team/discovery',
        label: 'Book Enterprise Demo',
        description: 'Custom integration, SLA support, and dedicated onboarding.',
      },
    },
    assets: {
      output_dir: 'assets',
      diagrams: {
        enabled: true,
        format: 'all',
        auto_detect: true,
      },
      social_cards: {
        enabled: true,
        theme: 'dark',
        sizes: [
          { name: 'og', width: 1200, height: 630 },
          { name: 'twitter', width: 1200, height: 675 },
          { name: 'github', width: 800, height: 400 },
        ],
      },
    },
  };

  // 5. Write config file
  const yamlContent = yamlStringify(config, {
    lineWidth: 100,
    defaultStringType: 'QUOTE_DOUBLE',
    defaultKeyType: 'PLAIN',
  });

  const header = `# devsetgo Configuration
# Generated by devsetgo init — customize these values for your project.
# Documentation: https://github.com/abdullahbilal-y/devsetgo#configuration
\n`;

  await safeWriteFile(configPath, header + yamlContent, { overwrite: options.force });
  log.success(`Configuration written to devsetgo.config.yaml`);

  // 6. Create .devsetgo directory
  await ensureDir(join(absRoot, '.devsetgo'));
  log.success('Created .devsetgo/ directory');

  // 7. Add .devsetgo to .gitignore if needed
  const gitignorePath = join(absRoot, '.gitignore');
  if (existsSync(gitignorePath)) {
    const gitignore = await readFileContent(gitignorePath);
    if (!gitignore.includes('.devsetgo')) {
      await safeWriteFile(gitignorePath, gitignore.trimEnd() + '\n\n# devsetgo\n.devsetgo/\n', {
        overwrite: true,
      });
      log.success('Added .devsetgo/ to .gitignore');
    }
  }

  // 8. Summary
  log.section('Next Steps');
  console.log('');
  console.log('  1. Edit devsetgo.config.yaml with your project details');
  console.log('  2. Add @playground annotations to your code snippets');
  console.log('  3. Run "devsetgo build" to generate everything');
  console.log('');
}
