/**
 * devsetgo — Playground Demos
 *
 * Sample functions that this repo's own docs site turns into runnable
 * examples. Kept out of `src/index.ts` so the published library API stays
 * limited to the tool itself.
 *
 * Every function here must be self-contained: the browser sandbox has no
 * imports, no network, and no file access.
 */

/**
 * @playground {"title": "Start here — what this page is", "category": "Introduction", "runnable": true}
 * A short explanation of what you are looking at. Edit any example and press Run.
 */
export function startHere(): void {
  console.log('This page was generated by devsetgo from the source of this repo.');
  console.log('');
  console.log('Each example below is a real function from src/demos.ts.');
  console.log('They run inside QuickJS, a small JavaScript engine compiled to');
  console.log('WebAssembly, running in your browser. No server is involved.');
  console.log('');
  console.log('The sandbox has no network, no file access, and no imports,');
  console.log('so every example has to stand on its own.');
  console.log('');
  console.log('Try it: change something above and press Run (or Ctrl+Enter).');
}

/**
 * @playground {"title": "How devsetgo prepares your code", "category": "How it works", "runnable": true}
 * The real transformation devsetgo applies to every example before publishing it.
 */
export function prepareCodeDemo(): void {
  // A simplified copy of src/playground/wasm-compiler.ts. The sandbox cannot
  // import the real one, so the logic is inlined here.
  function stripExports(code: string): string {
    return code.replace(/^[ \t]*export\s+default\s+/gm, '').replace(/^[ \t]*export\s+/gm, '');
  }

  function appendCallIfMissing(code: string): string {
    const declaration = /^(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/m.exec(code);
    if (!declaration) return code;

    const name = declaration[1];

    // Only a call at the start of a line counts. Searching the whole body
    // would match a recursive call and wrongly conclude it already runs.
    const withoutDeclaration = code.replace(/^(?:async\s+)?function\s+[A-Za-z_$][\w$]*\s*\(/gm, '');
    const alreadyCalled = new RegExp('^(?:await\\s+|void\\s+)?' + name + '\\s*\\(', 'm');

    return alreadyCalled.test(withoutDeclaration) ? code : code + '\n\n' + name + '();';
  }

  const input = [
    'export function fib(n) {',
    '  return n <= 1 ? n : fib(n - 1) + fib(n - 2);',
    '}',
  ].join('\n');

  console.log('INPUT — what you wrote:');
  console.log(input);
  console.log('');

  const output = appendCallIfMissing(stripExports(input));

  console.log('OUTPUT — what the playground runs:');
  console.log(output);
  console.log('');
  console.log('Two changes were made:');
  console.log('  1. "export" removed — the sandbox has no module system.');
  console.log('  2. "fib();" added — otherwise nothing would happen on Run.');
  console.log('');
  console.log('Note that fib(n - 1) inside the body did NOT count as a call.');
  console.log('Getting that wrong makes every recursive example print nothing.');
}

/**
 * @playground {"title": "The escape-character trap", "category": "How it works", "runnable": true}
 * A real bug from this codebase, reproduced so you can see it happen.
 */
export function escapeTrapDemo(): void {
  // The browser runtime is written inside a template literal. Inside one,
  // `\s` is not a recognised escape, so JavaScript collapses it to `s`.
  //
  // ESLint's no-useless-escape rule flags exactly this, which is the point:
  // had the linter been in place, the original bug would never have shipped.
  // Disabled here because reproducing the mistake is the whole demo.
  // eslint-disable-next-line no-useless-escape
  const insideTemplate = `\s+`;
  const written = 'What the source says:      \\s+';

  console.log(written);
  console.log('What actually gets emitted: ' + insideTemplate);
  console.log('');
  console.log('So a pattern meant as /^export\\s+/ shipped as /^exports+/,');
  console.log('which matches the literal text "exports" and nothing else.');
  console.log('');
  console.log('No error is raised anywhere. The regex simply never matches.');
  console.log('The fix is doubling every backslash; the test asserts on the');
  console.log('generated output rather than the source, because that is the');
  console.log('only place the mistake is visible.');
  console.log('');
  console.log('Postscript: ESLint flags this line. The linter added in v2');
  console.log('would have caught the original bug before it ever shipped.');
}

/**
 * @playground {"title": "Word frequency counter", "category": "Examples", "runnable": true}
 * An ordinary pure function — the kind this tool is actually good at showing.
 */
export function wordFrequency(
  text = 'the quick brown fox jumps over the lazy dog the fox',
): object {
  const counts: Record<string, number> = {};

  for (const word of text.toLowerCase().split(/\s+/).filter(Boolean)) {
    counts[word] = (counts[word] ?? 0) + 1;
  }

  const ranked = Object.entries(counts)
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, 5);

  console.log('Input: ' + text);
  console.log('');
  console.log('Top 5 words:');
  for (const [word, count] of ranked) {
    console.log('  ' + word.padEnd(8) + count);
  }

  return Object.fromEntries(ranked);
}

/**
 * @playground {"title": "Human-readable file sizes", "category": "Examples", "runnable": true}
 * The formatting helper devsetgo uses when reporting build output sizes.
 */
export function formatBytesDemo(): void {
  function formatBytes(bytes: number): string {
    if (bytes === 0) return '0 B';

    const units = ['B', 'KB', 'MB', 'GB'];
    const k = 1024;
    const i = Math.floor(Math.log(bytes) / Math.log(k));

    return (bytes / Math.pow(k, i)).toFixed(i > 0 ? 1 : 0) + ' ' + units[i];
  }

  for (const size of [0, 1, 999, 1024, 15360, 736142, 5_242_880, 3_221_225_472]) {
    console.log(String(size).padStart(12) + '  ->  ' + formatBytes(size));
  }
}
